server:
  port: 8081

spring:
  application:
    name: GATEWAY
  main:
    web-application-type: reactive
  cloud:
    gateway:
      global-filter:
        websocket-routing:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: idea
          uri: http://localhost:8082
          predicates:
            - Path=/ideas/**
          filters:
            - StripPrefix=1
        - id: vacation
          uri: http://localhost:8083
          predicates:
            - Path=/vacations/**
          filters:
            - StripPrefix=1
        - id: sequrity
          uri: http://localhost:8084
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1


