server:
  port: 8081

spring:
  application:
    name: GATEWAY
  main:
    web-application-type: reactive
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: 990153823815348234
            client-secret: AF_Kty4BiqX9XPbyQl_OcZSUxKb6Ferc
            issuer-uri: https://discord.com/api/oauth2/authorize
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/discord
            scope:
              - identify
            client-name: broomRoom
        provider:
          discord:
            authorizationUri: https://discordapp.com/api/oauth2/authorize
            token-uri: https://discordapp.com/api/oauth2/token
            user-info-uri: https://discordapp.com/api/users/@me
            user-name-attribute: username
  cloud:
    gateway:
      global-filter:
        websocket-routing:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:
        - id: IDEAS
          uri: lb://IDEAS
          predicates:
            - Path=/ideas/**
          filters:
            - StripPrefix=1
        - id: VACATIONS
          uri: lb://VACATIONS
          predicates:
            - Path=/vacations/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8089/eureka
