server:
  port: 8082

spring:
  application:
    name: IDEAS
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/electricBroomsBD2
    username: postgres
    password: worfa

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8089/eureka