server:
  port: 8082

spring:
  application:
    name: IDEA
  data:
    rest:
      basePath: /api
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/electricBroomsBD2
    username: postgres
    password: worfa