server:
  port: 8083

spring:
  application:
    name: VACATIONS
  data:
    rest:
      basePath: /api
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/electricBroomsBD2
    username: postgres
    password: worfa
    hikary:
      connectionTimeout: 20000
      maximumPoolSize: 5